project:
  type: book
  output-dir: output
  resources: ../data_simulation/

book:
  title: "Tagebuchstudien und Mehrebenenmodelle"
  author: "Dr. Francisco Wilhelm"
  date: "February 2025"
  chapters:
    - index.qmd
    #- Einleitung.qmd
    - 01 Data Preparation Item Level.qmd
    - 02 Descriptive Statistics.qmd
    - 03 Hypotheses Tests.qmd
    - 00 Data Wrangling Basics.qmd
    #- 04 Hypotheses Tests_Erweiterungen.qmd
    #- 05 Ausblick.qmd

# bibliography: references.bib


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
