---
title: "Einleitung"
format: html
---

# Einleitung

Dieses Dokument enthält Anleitungen und Übungen zur Analyse von Daten aus Tagebuchstudien mittels Mehrebenenmodellen. Es ist im Rahmen des Seminars zu Tagebuchstudien in Psychologie an der Uni Bern entstanden.

## Voraussetzungen

Materialien: 

- RStudio (erstellt RStudio 2024.12.0, Build 467)
- R (erstellt mit R 4.4.2)
- Installation von Paketen mit dem Code unten.


Kenntnisse:

- Data Wrangling in R, Umgang mit R-Notebooks, s. Anhang: Data Wrangling, sowie https://methodenlehre.github.io/einfuehrung-in-R/
- Statistisches Wissen zu linearen Modellen (Regressionen) und Testkonstruktion (Likert-Skalen, Reliabilitätsanalyse)

### Installation von R-Paketen, die im Kurs verwendet werden

Der Code unten installiert, falls noch nicht vorhanden, den "pacman" Paketmanager und danach alle R-Pakete, die für den Kurs benötigt werden.

```{r}
#| eval: false
if (!require("pacman")) install.packages("pacman")

pacman::p_load(devtools)
if (!require("multilevelmediation")) devtools::install_github("falkcarl/multilevelmediation")
if (!require("franzpak")) devtools::install_github("franciscowilhelm/franzpak")

pacman::p_load(lmerTest, haven, brms, psych,
               sjmisc, sjlabelled, sjPlot, writexl, broom.mixed, qgraph,
               tidyverse, multilevelTools, parameters, devtools,
               multilevelmediation)
```

