# detach("package:conflicted", unload = TRUE, character.only = TRUE)
# unloadNamespace("conflicted")

# conflicted::conflicts_prefer(tibble::add_case)
# conflicted::conflicts_prefer(ggplot2::alpha)
# conflicted::conflicts_prefer(brms::ar)
# conflicted::conflicts_prefer(brms::cs)
# conflicted::conflicts_prefer(Matrix::expand)
# conflicted::conflicts_prefer(dplyr::filter)
# conflicted::conflicts_prefer(purrr::is_empty)
# conflicted::conflicts_prefer(dplyr::lag)
# conflicted::conflicts_prefer(lmerTest::lmer)
# conflicted::conflicts_prefer(brms::ngrps)
# conflicted::conflicts_prefer(Matrix::pack)
# conflicted::conflicts_prefer(tidyr::replace_na)
# conflicted::conflicts_prefer(stats::step)